#!/bin/bash
# Quick Start Guide for ArthaSetu

echo "========================================="
echo "ArthaSetu - Quick Start Guide"
echo "========================================="
echo ""

echo "1. STARTING THE SERVER"
echo "   cd /path/to/ArthaSetu"
echo "   python start_server.py"
echo ""

echo "2. OPEN IN BROWSER"
echo "   http://localhost:5000"
echo ""

echo "3. LOGIN OPTIONS"
echo "   "
echo "   Option A: Use Demo Account"
echo "     Email: demo@arthsetu.com"
echo "     Password: demo123"
echo "   "
echo "   Option B: Create New Account"
echo "     Click 'Register' button"
echo "     Enter your details"
echo ""

echo "4. EXPLORE FEATURES"
echo "   "
echo "   Dashboard:"
echo "     - See portfolio overview"
echo "     - Monitor real-time values"
echo "     - View top recommendations"
echo "   "
echo "   Stock Analyzer:"
echo "     - Search stocks (TCS, INFY, RELIANCE)"
echo "     - Get AI buy/sell recommendations"
echo "     - Add to portfolio instantly"
echo "   "
echo "   My Portfolio:"
echo "     - Add new stocks"
echo "     - Track holdings"
echo "     - Monitor concentration risk"
echo "   "
echo "   Top Picks:"
echo "     - See 4 AI-selected stocks"
echo "     - Check confidence scores"
echo "     - View market sentiment"
echo "   "
echo "   Sectors:"
echo "     - Analyze sector rotation"
echo "     - See BULLISH/BEARISH ratings"
echo "     - Find best sector opportunities"
echo ""

echo "5. API TESTING (Optional)"
echo "   "
echo "   Health Check:"
echo "     curl http://localhost:5000/api/health"
echo "   "
echo "   Stock Analysis:"
echo "     curl http://localhost:5000/api/stock/TCS"
echo "   "
echo "   Top Recommendations:"
echo "     curl http://localhost:5000/api/market/recommendations"
echo ""

echo "6. COMMON TASKS"
echo "   "
echo "   Add Stock to Portfolio:"
echo "     1. Go to 'Stock Analyzer'"
echo "     2. Search stock symbol"
echo "     3. Click 'Add to Portfolio'"
echo "     4. Enter quantity and price"
echo "     5. Confirm to save"
echo "   "
echo "   View Analysis:"
echo "     1. Go to 'Dashboard'"
echo "     2. See recommendations"
echo "     3. Click on stock for details"
echo "     4. Check technical indicators"
echo "   "
echo "   Monitor Performance:"
echo "     1. Go to 'My Portfolio'"
echo "     2. View all holdings"
echo "     3. Check sector breakdown"
echo "     4. See concentration analysis"
echo ""

echo "7. KEY FEATURES"
echo "   ✓ Real-time stock prices (yfinance)"
echo "   ✓ Multi-agent AI analysis (4 agents)"
echo "   ✓ Technical indicators (RSI, MACD, etc.)"
echo "   ✓ Sentiment analysis (news-based)"
echo "   ✓ Portfolio risk analysis"
echo "   ✓ User authentication"
echo "   ✓ Responsive design"
echo "   ✓ Beautiful UI"
echo ""

echo "8. TROUBLESHOOTING"
echo "   "
echo "   Server not starting?"
echo "     - Check Python version (3.8+ needed)"
echo "     - Install dependencies: pip install -r requirements.txt"
echo "     - Verify port 5000 is free"
echo "   "
echo "   API returning errors?"
echo "     - Check Flask console output"
echo "     - Ensure you're logged in"
echo "     - Verify stock symbols are valid"
echo "   "
echo "   Stocks not analyzing?"
echo "     - Check internet connection (needs yfinance)"
echo "     - Use valid NSE symbols for Indian stocks"
echo "     - Wait 3-5 seconds for analysis"
echo ""

echo "========================================="
echo "Platform Ready! Visit http://localhost:5000"
echo "========================================="
